server:
  port: 82

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/
  
zuul:
  ignored-services:
    cliente-circuit-breaker
  routes:
    cliente:
      path: /cliente/**
      serviceId: cliente
    holamundo:
      path: /holamundo/**
      #Para mapeo de las url directas a un servicio
      #url: http://localhost:8080/
      
      #Para mapeo de servicios registrados en Eureka 
      serviceId: holamundo
      sensitive-headers: 
      #custom-sensitive-headers: true
  ignore-security-headers: false
  